### PR TITLE
iPhone X support for navbar

### PR DESCRIPTION
**Pull request by jberglinds**
#22.
* Extends page to edges
* Uses safe-area env var when available
skarmavbild 2017-12-13 kl 11 32 23

### CODE REVIEW

**Comment by aronstrandberg** [comment]
@jberglinds Can you please rebase this on the branch `as/redesign-navbar-transparent-scroll`?

**Comment by jberglinds** [comment]
Sure, done!
@aronstrandberg

**Comment by aronstrandberg** [comment]
can you post a new screenshot? I don't know how to do your crazy device thing

**Comment by jberglinds** [comment]
I'll fix it when I get home. If you have Xcode installed you can open the simulator from there.

**Comment by jberglinds** [comment]
skarmavbild 2017-12-13 kl 16 10 44
skarmavbild 2017-12-13 kl 13 03 08

**Pull request merged**
